import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, Sparkles } from 'lucide-react'
import { buildPageMetadata } from '@/lib/seo'
import { EditableSiteShell } from '@/editable/shell/EditableSiteShell'
import { EditableLocalSignupForm } from '@/editable/components/EditableLocalAuthForms'
import { pagesContent } from '@/editable/content/pages.content'
export async function generateMetadata(): Promise<Metadata>{return buildPageMetadata({path:'/signup',title:'Sign up',description:pagesContent.auth.signup.metadataDescription})}
export default function SignupPage(){return <EditableSiteShell><main className="min-h-screen bg-[var(--slot4-page-bg)] px-5 py-10 sm:px-8 lg:px-12"><section className="mx-auto grid max-w-[var(--editable-container)] overflow-hidden rounded-[3rem] bg-[var(--slot4-dark-bg)] text-white lg:min-h-[680px] lg:grid-cols-[.9fr_1fr]"><div className="m-3 rounded-[2.4rem] bg-white p-7 text-[var(--slot4-page-text)] sm:m-5 sm:p-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--slot4-muted-text)]">Members</p><h1 className="mt-4 text-3xl font-bold tracking-[-.06em]">{pagesContent.auth.signup.formTitle}</h1><EditableLocalSignupForm/><p className="mt-7 text-sm text-[var(--slot4-muted-text)]">Already collecting? <Link href="/login" className="font-bold text-[var(--slot4-page-text)] underline underline-offset-4">{pagesContent.auth.signup.loginCta} <ArrowRight className="inline h-3.5 w-3.5"/></Link></p></div><div className="flex flex-col justify-center p-8 sm:p-14"><Sparkles className="h-7 w-7 text-[var(--slot4-accent)]"/><p className="mt-10 text-xs font-bold uppercase tracking-[.2em] text-[var(--slot4-accent)]">{pagesContent.auth.signup.badge}</p><h2 className="mt-5 max-w-xl text-5xl font-bold leading-[.85] tracking-[-.07em] sm:text-7xl">A better shelf for the internet.</h2><p className="mt-7 max-w-md text-base leading-7 text-white/65">{pagesContent.auth.signup.description}</p></div></section></main></EditableSiteShell>}
