import Link from 'next/link'
import { ArrowRight, Bookmark, Check, ExternalLink, Search, Sparkles } from 'lucide-react'
import type { SitePost } from '@/lib/site-connector'
import type { HomeTimeSection } from '@/lib/task-data'
import type { TaskKey } from '@/lib/site-config'
import { getEditablePostImage, postHref, toPlainText } from '@/editable/cards/PostCards'
import { EditableReveal } from '@/editable/shell/EditableReveal'
import { CATEGORY_OPTIONS } from '@/lib/categories'
type Props={primaryTask:TaskKey;primaryRoute:string;posts:SitePost[];timeSections:HomeTimeSection[]}
const wrap='mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-8 lg:px-12'
const excerpt=(p:SitePost)=>toPlainText(p.summary || (p.content && typeof p.content==='object' ? String((p.content as Record<string,unknown>).description||'') : '')).slice(0,125)
const cat=(p:SitePost)=>p.tags?.[0]||((p.content&&typeof p.content==='object'&&typeof (p.content as Record<string,unknown>).category==='string')?(p.content as Record<string,string>).category:'Collection')
function Card({post,task,route,index}:{post:SitePost;task:TaskKey;route:string;index:number}){const image=getEditablePostImage(post);return <EditableReveal index={index}><Link href={postHref(task,post,route)} className="group block rounded-[2rem] bg-white p-3 transition hover:-translate-y-1"><div className="relative aspect-[4/3] overflow-hidden rounded-[1.45rem] bg-[var(--slot4-media-bg)]">{image?<img src={image} alt="" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/>:null}<span className="absolute left-3 top-3 rounded-full bg-[var(--slot4-accent)] px-3 py-1 text-[10px] font-bold uppercase tracking-wider">{cat(post)}</span></div><div className="p-3 pb-2"><h3 className="line-clamp-2 text-xl font-bold leading-[.98] tracking-[-.05em]">{post.title}</h3>{excerpt(post)?<p className="mt-3 line-clamp-2 text-sm leading-6 text-[var(--slot4-muted-text)]">{excerpt(post)}</p>:null}<span className="mt-4 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider">Open resource <ArrowRight className="h-3.5 w-3.5"/></span></div></Link></EditableReveal>}
export function EditableHomeHero({primaryRoute,posts}:Props){const glimpse=posts.slice(0,3);return <section className="overflow-hidden bg-[var(--slot4-page-bg)]"><div className={`${wrap} grid gap-10 py-16 sm:py-24 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-28`}><EditableReveal><p className="text-xs font-bold uppercase tracking-[.2em]">Collections · Members</p><h1 className="mt-6 max-w-3xl text-6xl font-bold leading-[.82] tracking-[-.075em] sm:text-7xl lg:text-[6.7rem]">Useful corners of the internet, kept together.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[var(--slot4-muted-text)]">A growing set of hand-picked bookmarks, tools, essays and resources for curious people.</p><div className="mt-9 flex flex-wrap gap-3"><Link href={primaryRoute} className="inline-flex items-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3.5 text-sm font-bold text-white">Explore collections <ArrowRight className="h-4 w-4"/></Link><Link href="/search" className="inline-flex items-center gap-2 rounded-full border border-[var(--editable-border)] bg-white px-6 py-3.5 text-sm font-bold"><Search className="h-4 w-4"/>Search resources</Link></div></EditableReveal><EditableReveal index={1}><div className="relative grid grid-cols-2 gap-3 rounded-[3rem] bg-[var(--slot4-panel-bg)] p-4 sm:p-6">{glimpse.length?glimpse.map((p,i)=><div key={p.id||p.slug} className={`overflow-hidden rounded-[1.8rem] bg-white ${i===0?'col-span-2 aspect-[16/8]':'aspect-square'}`}><img src={getEditablePostImage(p)} alt="" className="h-full w-full object-cover"/></div>):<div className="col-span-2 flex aspect-[16/9] items-center justify-center rounded-[2rem] bg-[var(--slot4-accent)]"><Bookmark className="h-16 w-16"/></div>}<div className="absolute -bottom-4 -left-4 rounded-full bg-[var(--slot4-accent)] px-5 py-3 text-xs font-bold">{posts.length || 'Fresh'} finds to explore</div></div></EditableReveal></div></section>}
export function EditableStoryRail({primaryRoute}:Props){const categorySlugs=['technology','business','education','finance','travel','lifestyle'];const categories=categorySlugs.map(slug=>CATEGORY_OPTIONS.find(item=>item.slug===slug)).filter((item):item is {name:string;slug:string}=>Boolean(item));return <section className="border-y border-[var(--editable-border)] bg-white py-5"><div className={`${wrap} flex gap-3 overflow-x-auto`}>{categories.map((category,i)=><EditableReveal key={category.slug} index={i}><Link href={`${primaryRoute}?category=${encodeURIComponent(category.slug)}`} className="inline-flex whitespace-nowrap rounded-full border border-[var(--editable-border)] px-5 py-3 text-sm font-bold transition hover:bg-[var(--slot4-accent)]">{category.name}</Link></EditableReveal>)}</div></section>}
export function EditableMagazineSplit({primaryTask,primaryRoute,posts}:Props){return <section className="bg-[var(--slot4-panel-bg)] py-20 sm:py-28"><div className={wrap}><EditableReveal><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em]">A better way to keep tabs</p><h2 className="mt-5 text-5xl font-bold leading-[.86] tracking-[-.07em] sm:text-6xl">Save the good stuff. Find it again.</h2></div><div className="grid gap-4 sm:grid-cols-2">{['Hand-picked collections','Useful context, not noise','Always ready to share','Built for serendipity'].map((x,i)=><EditableReveal index={i} key={x}><div className="rounded-[2rem] bg-white p-6"><Check className="h-5 w-5"/><h3 className="mt-7 text-xl font-bold tracking-[-.04em]">{x}</h3><p className="mt-3 text-sm leading-6 text-[var(--slot4-muted-text)]">Thoughtful links that make an internet rabbit hole worth your time.</p></div></EditableReveal>)}</div></div></EditableReveal><div className="mt-16 flex items-end justify-between"><h2 className="text-4xl font-bold tracking-[-.06em]">Featured collections</h2><Link href={primaryRoute} className="hidden text-sm font-bold sm:inline">See all <ArrowRight className="inline h-4 w-4"/></Link></div><div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{posts.slice(0,6).map((p,i)=><Card key={p.id||p.slug} post={p} task={primaryTask} route={primaryRoute} index={i}/>)}</div></div></section>}
export function EditableTimeCollections({primaryTask,primaryRoute,posts,timeSections}:Props){const picks=[...posts,...timeSections.flatMap(x=>x.posts)].slice(0,8);return <section className="py-20 sm:py-28"><div className={wrap}><EditableReveal><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.2em]">From the shelves</p><h2 className="mt-4 text-5xl font-bold tracking-[-.07em]">Worth opening today.</h2></div><p className="max-w-sm text-sm leading-6 text-[var(--slot4-muted-text)]">Fresh additions from across our collections, selected for a little more signal.</p></div></EditableReveal><div className="mt-9 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{picks.map((p,i)=><Card key={`${p.id||p.slug}-${i}`} post={p} task={primaryTask} route={primaryRoute} index={i}/>)}</div></div></section>}
export function EditableHomeCta(){return <section className="px-5 pb-20 sm:px-8 lg:px-12"><EditableReveal><div className="mx-auto max-w-[var(--editable-container)] rounded-[3rem] bg-[var(--slot4-dark-bg)] px-7 py-16 text-white sm:px-12 sm:py-24"><Sparkles className="h-7 w-7 text-[var(--slot4-accent)]"/><h2 className="mt-7 max-w-3xl text-5xl font-bold leading-[.86] tracking-[-.07em] sm:text-7xl">Keep the internet you want to come back to.</h2><Link href="/signup" className="mt-9 inline-flex rounded-full bg-[var(--slot4-accent)] px-6 py-3.5 text-sm font-bold text-[var(--slot4-page-text)]">Join the collection <ExternalLink className="ml-2 h-4 w-4"/></Link></div></EditableReveal></section>}
